### ISSUE TITLE
Pipe vs StdInput stream

### ISSUE THREAD

**Issue by nathan-c** [rosenbjerg/FFMpegCore#214] opened 2021-05-25 11:18 UTC
Problem: I have a video in a byte array and would like to use ffprobe to get information such as format, length & codec. 

If the video is an mp4 the code below throws exception `FFMpegCore.Exceptions.FFMpegException: FFProbe process returned exit status 1` and the ffprobe error is 
```
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x560ee83aaf00] moov atom not found
unix:/tmp/CoreFxPipe_FFMpegCore_7f37b2b3-654d-4f5f-8213-de95552b246e: Invalid data found when processing input
```
``` csharp
await using var mp4 = new MemoryStream(bytes);
var m4aMediaInfo = await FFProbe.AnalyseAsync(mp4);
```

I found this explanation of the moov atom https://github.com/rosenbjerg/FFMpegCore/issues/145#issuecomment-743916937 and understand the problem here is we use a non-seekable pipe and perhaps in my case the moov atom is not at the beginning of the file. Is there another way I can feed a byte array into ffprobe without writing a file to disk and passing path?

If I manually call ffprobe using the below code then it works correctly and returns the media info. Is there a way to use the `StandardInput` stream as opposed to going via a pipe?

``` csharp
var dir = "./Multimedia/TestFiles/";

var p = new Process
{
	StartInfo = new ProcessStartInfo("ffprobe",
		"-loglevel error -print_format json -show_format -sexagesimal -show_streams -")
	{
		RedirectStandardInput = true,
		RedirectStandardOutput = true,
		RedirectStandardError = true,
		CreateNoWindow = true,
		UseShellExecute = false,
	},
};

p.Start();
var stdIn = p.StandardInput;

await using var mp4 = new MemoryStream(bytes);
await mp4.CopyToAsync(stdIn.BaseStream);

await p.WaitForExitAsync();

MediaAnalysis output = await ParseOutputAsync(p.StandardOutput.BaseStream);
```

**Comment by rosenbjerg** [comment] 2021-07-10 15:28
That is currently not supported, but something I have considered before. I didn't have the need for it though, so I didn't go any further with it. 
This is however functionality that would be welcome in this library, so if you want to take a stab at implementing it, you are very welcome :)

**Comment by rosenbjerg** [comment] 2021-07-12 15:41
Duplicate of #213

**Comment by rosenbjerg** [comment] 2021-08-07 07:48
I think #213 is asking for something entirely different from what you suggest. 
If you think there are pros to using the StandardInput/StandardOutput streams of the `Process` instead of the NamedPipe approach currently available in this library, it may be a very good addition :)

**Comment by rosenbjerg** [comment] 2021-08-07 07:50
@max619 Interesting suggestion? :)

**Comment by max619** [comment] 2021-08-07 12:59
@rosenbjerg, Hi!

I'm not sure what can cause such a behaviour when using pipes, but works fine with stdinput. As I understand std io streams should work the same way as pipes. They both work as single-direction streams withour random access support. There might be some issues with platform dependent implementations of pipes in .Net Core.

I would suggest to test @nathan-c's case under different platforms and examine it carefully. I think that problem might be in somewhere else rather then in pipes themselves.

Also, when i was starting working on pipes, i tried to use std io streams but faced issues under Windows. 
Data was corrupted or something similar, then i tried to use pipes because that approach was looking more reliable. Hovewer, now we have quite a lot of issues with them. And i'm not sure if pipes work unreliably, or the vast majority of issues about inablity to work with streams and mp4 streams. I think it would be nice to add some validation in library for that common cases, to reduce amount of issues with same problems (and improve docs with adding examples). 

Obviously we can provide support of std io streams, it doesn't look like a very complex task to impelement it. 

Unfortuanately, i do not have a lot of time right now to do that myself. A few months ago i started working on adding support of reading frames from videos in any pixel format, and, as you can see, didn't finished it yet :)

**Comment by nathan-c** [comment] 2022-01-13 13:39
Sorry for the radio silence, I ended up going in a different direction back when I raised this issue (and not using ffprobe) however, I have ended up coming back to this. 

While experimenting with using stdin/stdout I found that while ffprobe does not error, for certain file types (e.g. MP3) it will not return the duration (which is what I am interested in). This appears to be a [limitation](https://trac.ffmpeg.org/ticket/4358) of how ffprobe determines the duration of the container / streams. As such, I now write my media to a temp file and pass the filename to ffprobe which gets me everything that I need but with the downside of the extra disk IO.

In order to use stdin/stdout I had to remove the `Instances` dependency because it doesn't support streaming bytes to stdin so its not a super simple change (though it is also not that large as `Instances` is a fairly small library).

Feel free to close the issue unless others are interested.

**Closed as completed** 2022-04-15 18:38 UTC
