### ISSUE TITLE
Custom ffprobe arguments

### ISSUE THREAD

**Issue by vfrz** [rosenbjerg/FFMpegCore#405] opened 2023-02-18 18:36 UTC
Hi,
I'd like to set custom command argument for ffprobe but it's seems impossible right now.
Would it be possible for you to implement this feature please?

**Comment by rosenbjerg** [comment] 2023-02-21 16:28
Duplicate of #353

**Comment by rosenbjerg** [comment] 2023-02-21 16:28
Misread that one. No that is currently not supported

**Closed as completed** 2023-10-05 10:06 UTC
Labels: enhancement
