### ISSUE TITLE
Creating video from image files using JoinImageSequence is broken

### ISSUE THREAD

**Issue by TomSelleck101** [rosenbjerg/FFMpegCore#281] opened 2021-12-06 17:53 UTC
Howdy, 

I've tried to fix this based on a previous [issue](https://github.com/rosenbjerg/FFMpegCore/issues/107) (this [issue ](https://github.com/rosenbjerg/FFMpegCore/issues/243) also experiences the same problem and "solves" it by just directly calling the ffmpeg library).

Issue is pretty straight forward, I'm unable to create a valid video from images. Using the following code:

```
// Check if there are images to compile
IEnumerable<string> screenshotPaths = Directory.GetFiles(CurrentRecordingFolder)
                                                .Select(p => Path.GetFullPath(p));

if (screenshotPaths.Count() == 0)
{
    throw new Exception($"No images in recording folder \"{CurrentRecordingFolder}\"");
}

// Set the destination path
string recordingFolderAbsolute = Path.GetFullPath(CurrentRecordingFolder);
string videoDestinationPath = $"{recordingFolderAbsolute}\\capture.mp4";

// Create the video
IEnumerable<ImageInfo> imageSequence = screenshotPaths.Select(path => ImageInfo.FromPath(path));

FFMpeg.JoinImageSequence(videoDestinationPath, frameRate: 0.3, imageSequence.ToArray());
```

An output file is created, however it only contains two frames from the whole sequence. For example, if my CurrentRecordingFolder looks like this:

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/32855042/144896169-30cb8f62-56f5-4ec5-87ce-c62dca28cafb.png">

The output video looks like this:

![give_you_up](https://user-images.githubusercontent.com/32855042/144896362-b94c86be-6aae-481f-bf83-96f70d4f7da3.gif)

I've also tried the following code with no luck:

```
FFMpegArguments
    .FromConcatInput(screenshotPaths)
    .OutputToFile(videoDestinationPath, true,
        options =>
            options
            .WithConstantRateFactor(1)
        )
    .ProcessSynchronously();
```

**Comment by rosenbjerg** [comment] 2022-01-05 23:48
Can you try with a frameRate? Maybe 1.0? Just to find out if the problem is related to that, which I suspect

**Comment by rkaufman** [comment] 2022-03-18 16:47
I have the same issue. I did use the frameRate: 1.0. It produces a corrupt mp4 file. I reverted to a process driven approach. I put the argument string in as  -r 30 -i <directory here>/<file name here>%04d.png -pix_fmt yuv420p <output file name here>.

**Comment by TomSelleck101** [comment] 2022-03-18 17:00
Yup I just used a process approach too. Shame as I'd really prefer to use
this lib

**Comment by rosenbjerg** [comment] 2022-04-15 18:16
Version 4.8 has just been released, and contains fix for this issue :)

**Closed as completed by rosenbjerg** 2022-04-15 18:16 UTC
Labels: bug

**Comment by john-ds** [comment] 2022-11-02 15:56
I'm currently using Version 4.8 and am still experiencing this issue where only the first two images are shown in the output video...

```
FFMpeg.JoinImageSequence(dlg.FileName, frameRate: 1,
    ImageInfo.FromPath("01.png"),
    ImageInfo.FromPath("02.png"),
    ImageInfo.FromPath("03.png"),
    ImageInfo.FromPath("04.png")
);
```

**Comment by farukcan** [comment] 2024-10-15 12:07
Same problem. Only few images shown in the output video.

**Comment by farukcan** [comment] 2024-10-15 15:16
It's fixed the problem
```cs
            // create video from png frames use FFMpegCore
            FFMpegArguments
                .FromConcatInput(pngFiles, options => options.WithFramerate(frameRate))
                .OutputToFile(Path.Combine(projectDir, "output.mp4"), true,
                    options =>
                        options
                        .WithConstantRateFactor(1)
                        .ForcePixelFormat("yuv420p")
                    )
                .ProcessSynchronously();
```
